name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build
      
  test:
    runs-on: macos-14
    needs: build
    name: Test
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test
